<a href="https://colab.research.google.com/github/jambhalerutuja/machine-learning-with-python/blob/main/numpy_and_pandas1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
np.zeros((2,10),int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [4]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [5]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
np.random.rand(3,2)

array([[0.6046242 , 0.01731233],
       [0.41737775, 0.58998241],
       [0.61247863, 0.60117307]])

In [7]:
np.random.randn(3,2)

array([[-0.56298929, -1.48992191],
       [-0.50051724, -0.56413875],
       [ 1.23240063, -0.84954505]])

In [8]:
np.random.randint(1,5)

1

In [9]:
np.random.randint(30,100,50)

array([72, 59, 43, 39, 30, 56, 59, 38, 50, 69, 33, 90, 80, 65, 73, 44, 47,
       98, 70, 46, 52, 94, 78, 53, 46, 81, 91, 77, 59, 84, 35, 95, 63, 45,
       35, 88, 68, 48, 59, 32, 63, 60, 58, 48, 55, 74, 84, 31, 42, 72])

In [10]:
a=np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [11]:
b=np.random.randint(0,100,20)
b

array([51, 50, 67, 86, 60, 51, 97, 12, 57, 65, 81, 23, 17, 23, 36, 88, 31,
       87, 57, 30])

In [12]:
a.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [13]:
b.min()

12

In [14]:
b.argmin()

7

In [15]:
x=np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
x.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
x=np.random.rand(2,3)
x

array([[0.06697312, 0.11971518, 0.41531207],
       [0.84957371, 0.73189407, 0.19763187]])

In [18]:
x=np.arange(10,21)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])