<a href="https://colab.research.google.com/github/jambhalerutuja/machine-learning-with-python/blob/main/numpy_and_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [3]:
x=[[1,2,3,4],[5,6,7,8],[8,9,10]]
y=np.array(x)
y

<ipython-input-3-32be1c5689c3>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  y=np.array(x)


array([list([1, 2, 3, 4]), list([5, 6, 7, 8]), list([8, 9, 10])],
      dtype=object)

In [4]:
y

array([list([1, 2, 3, 4]), list([5, 6, 7, 8]), list([8, 9, 10])],
      dtype=object)

In [5]:
np.arange(1,8)

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [7]:
np.arange(1,47,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [8]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [9]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [10]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [11]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
np.zeros((2,10),int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [14]:
np.linspace(0,5,1)

array([0.])