<a href="https://colab.research.google.com/github/jambhalerutuja/machine-learning-with-python/blob/main/numpy_and_pandas_2_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x=np.arange(10,21)
x


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
x[3]

13

In [ ]:
x[3:8]

array([13, 14, 15, 16, 17])

In [ ]:
x[1:4]=100
x

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [ ]:
x[0:7]

array([ 10, 100, 100, 100,  14,  15,  16])

In [ ]:
subset_x=x[0:7]
subset_x

array([ 10, 100, 100, 100,  14,  15,  16])

In [ ]:
x=np.array([[11,22,33],[30,20,10],[2,4,6]])
x

array([[11, 22, 33],
       [30, 20, 10],
       [ 2,  4,  6]])

In [ ]:
x[2:]

array([[2, 4, 6]])

In [ ]:
x[2]

array([2, 4, 6])

In [ ]:
x[:,(1,2)]
x

array([[11, 22, 33],
       [30, 20, 10],
       [ 2,  4,  6]])

In [ ]:
x=np.arange(1,20)

In [ ]:
x+x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [ ]:
np.exp(x)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [ ]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [ ]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [ ]:
np.min(x)

1

In [ ]:
np.max(x)

19

In [ ]:
np.argmin(x)

0

In [ ]:
np.square(x)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [ ]:
np.std(x)

5.477225575051661

In [ ]:
np.var(x)

30.0

In [ ]:
np.mean(x)

10.0

In [ ]:
a=np.random.randn(3,4)
a

array([[ 1.5736635 , -1.12976198,  1.56779333,  1.23224157],
       [ 0.04700379,  0.64736447,  0.05969776, -0.46020049],
       [ 2.50162842,  0.59317832,  0.51635881,  0.94280456]])

In [ ]:
np.round(a,decimals=3)

array([[ 1.574, -1.13 ,  1.568,  1.232],
       [ 0.047,  0.647,  0.06 , -0.46 ],
       [ 2.502,  0.593,  0.516,  0.943]])

In [ ]:
sports=np.array(['golf','cricket','ftball','bsktball','golf','cricket','ftball'])
np.unique(sports)

array(['bsktball', 'cricket', 'ftball', 'golf'], dtype='<U8')